boot.o: boot.S multiboot.h x86_desc.h types.h idt.h
idt_wrap.o: idt_wrap.S
x86_desc.o: x86_desc.S x86_desc.h types.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h x86_desc.h types.h lib.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h rtc.h keyboard.h terminal.h paging.h
keyboard.o: keyboard.c keyboard.h types.h i8259.h lib.h terminal.h
lib.o: lib.c lib.h types.h
paging.o: paging.c paging.h types.h
rtc.o: rtc.c rtc.h i8259.h types.h lib.h
terminal.o: terminal.c terminal.h i8259.h types.h lib.h keyboard.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h paging.h
